### ISSUE TITLE
Exception: Exception: multiply: A[1] is -nan, but must not be nan!

### ISSUE THREAD

**Issue by AntonisKoutounids** [tidymodels/tidyposterior#31]
I am running an Hierarchical model with poisson family and this error appears. I could not find anywhere on the internet talking about this error.
I would like to know what this error means:

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:"                                                
"Chain 3: Exception: Exception: multiply: A[1] is -nan, but must not be nan!

**Comment by topepo** [comment]
This does not sound like an issue for this package. If it is, please re-open with a  minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.
